### ISSUE TITLE
Navigation Key Issue

### ISSUE THREAD

**Issue by shehrozchishty** [syedshiraz59/static-game-website#1]
Navigation key moves the character very slowly if the key is being pressed.

Should be able to move with ease. Don't have to strike the again and again to move the character up and down

**Comment by syedshiraz59** [comment]
![Screenshot 2023-05-09 111838](https://user-images.githubusercontent.com/132645971/237011227-f893e4d7-eac1-4643-b3dd-44995ad9473d.png)
![Screenshot 2023-05-09 111800](https://user-images.githubusercontent.com/132645971/237011234-e9225b48-8695-45be-b42c-722eb5047139.png)
this is a snippet code of problem that was i m changed. .
solution
![image](https://user-images.githubusercontent.com/132645971/237011674-c5b0e82a-762f-41bc-a3f3-4a9480f15b31.png)
![image](https://user-images.githubusercontent.com/132645971/237011835-edd2d3c6-3623-4c9c-99cf-c32f13ab7f35.png)
![image](https://user-images.githubusercontent.com/132645971/237011983-19ddf7e3-51bc-4213-a211-91c1d75c2b38.png)
 
Remove the callback functions passed to the movement functions to reduce the delay between movements.

Use requestAnimationFrame() to optimize the animation loop and reduce lag. This function synchronizes the animation with the browser's refresh rate.

Use CSS transitions to animate the character movement instead of changing the position of the character directly with JavaScript.
